import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Viðburður á næstunni</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body>
        <header className={styles.header}>

        </header>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Viðburðir á næstunni
            </h1>
            
            <p className={styles.description}>
              Get started by editing{' '}
              <code className={styles.code}>pages/index.js</code></p>
      </main>

      <footer className={styles.footer}>
        <a href=""> Forsíða </a>
        <a href="/Innskráning"> Innskráning </a>
        <a href="/Nyskraning"> Nýskráning </a>
      </footer>
      </body>
      
    </div>
  )
}
